### ISSUE TITLE
python3 and cPickle

### ISSUE THREAD

**Issue by alferca** [arcelien/pba#11]
File "pba/autoaugment/data_utils.py", line 185, in unpickle  File "pba/autoaugment/data_utils.py", line 185, in unpickle
    d = cPickle.load(fo)
NameError: name 'cPickle' is not defined

    d = cPickle.load(fo)
NameError: name 'cPickle' is not defined

**Comment by arcelien** [comment]
Sorry. I just pushed a commit that should hopefully resolve this.

**Comment by tienduchoang** [comment]
Hi @arcelien, got another error
```
fo = tf.gfile.Open(f, 'r').read()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte
```

**Comment by arcelien** [comment]
Do you have steps to reproduce?

Also, can you try reading with `rb` by replacing the line with: `fo = tf.gfile.Open(f, 'rb').read()`

**Comment by tienduchoang** [comment]
yes, i follow your reademe instruction and i am in reproductive step.
I try to read with 'rb'. but i got error like bellow:
1.
```
fo = tf.gfile.Open(f, 'rb').read()
d = pickle.load(fo)
```
```
TypeError: file must have 'read' and 'readline' attributes
```
2.
```
fo = tf.gfile.Open(f, 'rb').read()
d = pickle.loads(fo)
```
```
UnicodeDecodeError: 'ascii' codec can't decode byte 0x8b in position 6: ordinal not in range(128)
```
3. 
```
import _pickle as cPickle
fo = tf.gfile.Open(f, 'rb').read()
d = cPickle.load(fo, encoding='latin1')
```
```
TypeError: file must have 'read' and 'readline' attributes
```
I don't know how to solve their problem.

**Comment by arcelien** [comment]
Which shell command are you running specifically?

**Comment by tienduchoang** [comment]
bash scripts/table_1_cifar10.sh wrn_28_10

**Comment by arcelien** [comment]
I pushed a new fix and the command didn't crash for me. Sorry for the bugs.

**Comment by tienduchoang** [comment]
Hi @alferca . thank for your help. it works

**Comment by arcelien** [comment]
Glad to hear!
