### ISSUE TITLE
colab crashes when using a big dataset.

### ISSUE THREAD

**Issue by AlyShmahell** [arcelien/pba#16]
Hello,

I'm attempting to use this library with a dataset of 3700 hi-definition images, but google colab seems to crash, is there a limit on how much data the library can process?
I tried again with 37 images and it worked, so I assume it's a workload issue.

**Comment by arcelien** [comment]
Hmm, the code should only be loading one image with the code: `PIL.Image.open(image_path)`.

Perhaps you are loading all of the images somehow and running out of memory?

**Comment by AlyShmahell** [comment]
Hello @arcelien 
Thanks for the feedback.
I thought the way the current dataloader is implemented only supports loading all data at once, if that isn't the case then I will take another look at my code.
I recently realized there was a bug in my code that  made the colab notebook load the images for display, which created its own set of performance problems, after fixing the bug and doing some extensive tests I will know where the problem resides, and I will let you know.
Thanks again.

**Comment by arcelien** [comment]
The colab should not be using the entire dataloader, just loading a specific image.

If you try to run the full training code with your large dataset, you may get out of memory issues.
