### ISSUE TITLE
Evaluation part param set?

### ISSUE THREAD

**Issue by serereuk** [arcelien/pba#18]
Hi everyone, I've done some PBA searches for some datasets with the model wide resnet_40_2.
and I'm wondering that in evaluation part, (which uses wide_resnet_28_10 with the schedule from the search pbt_policy_ *.txt ) do I have to use the same parameter setting that I used in search part (lr, wd, epochs)?

**Comment by arcelien** [comment]
The number of epochs will stay the same at 200. The model hparams is dependent on the model. See `pba/scripts/table_1_cifar10.sh` for the hparams used for each model architecture. For example, ResNet-28-10 uses `lr=0.1` and `wd=0.0005` (on line 26).

**Comment by serereuk** [comment]
Thanks!! I'll try as you said!
