### ISSUE TITLE
Tensorflow version issue?

### ISSUE THREAD

**Issue by serereuk** [arcelien/pba#19]
Hi I tried to search schedule with the datasets with Resnet-20.

However I got one error with Namespace issues and one error with tensorflow issue. 

First, in setup.py line 180, I think the code make the resnet_size to FLAGS and it pass to num_filters, but it doesn't work. When I change 'FLAGS.resnet_size'  to just 20, it works.

Second, I use tensorflow-gpu 1.4.1. In resnet.py line 483, tf.reduce_mean doesn't work with wrong parameter errors. It works when I change keepdims -> keep_dims

Thanks

**Comment by arcelien** [comment]
Thanks for the catch, I updated the `num_filters` hparam. For tensorflow version, I've tested this with 1.10.0 and 1.11.0, so you may need to update to a later version.

**Comment by serereuk** [comment]
Thanks!
