### ISSUE TITLE
Script for visualizing the probability and magnitude hyperparameters

### ISSUE THREAD

**Issue by hanzhi713** [arcelien/pba#21]
Could you please publish the script for drawing these fancy visualizations?

| Probability Hyperparameters over Time             | Magnitude Hyperparameters over Time              |
| ------------------------------------------------- | ------------------------------------------------ |
| ![](/arcelien/pba/raw/master/figs/cifar-prob.png) | ![](/arcelien/pba/raw/master/figs/cifar-mag.png) |

**Comment by arcelien** [comment]
This was done in google sheets / charts :)

**Comment by hanzhi713** [comment]
Alright. I will manage to write a Python script to plot similar graphs using matplotlib. It helps to gain some insights into the augmentation schedule learned.
