### ISSUE TITLE
Find out which policy performed best after search

### ISSUE THREAD

**Issue by bmitzkus** [arcelien/pba#31]
After running the search, is there an easy way to find out which of the `pbt_policy_n.txt` files stores the best policy?

Thanks

**Comment by arcelien** [comment]
The easiest way I know of is to open tensorboard on the result folder which should show the performance metrics of all trials. The trial numbers in tensorboard correspond to the index in the `pbt_policy_*.txt` files.

**Comment by bmitzkus** [comment]
Thanks a lot :)
