### ISSUE TITLE
Kindly update to use newer Python

### ISSUE THREAD

**Issue by impredicative** [arcelien/pba#5]
As noted at https://pythonclock.org/ , Python 2.7 expires at the end of the year. It is therefore incomprehensible that it was used for this otherwise interesting project. Kindly consider updating it to use a current version of Python, i.e. 3.7 or maybe 3.6 at the oldest. The repo's users shouldn't have to independently go through the pain of converting it. Failing this, it's not possible to integrate the code in a modern codebase. Thanks.

**Comment by arcelien** [comment]
Thanks for the suggestion, I'll look into adding python 3 functionality. Unfortunately some prior work I'm importing used python 2, so that would have to be converted as well.

**Comment by arcelien** [comment]
Resolved in #8!
